In [6]:
import torch
print(torch.__version__)

2.4.1+cpu


In [7]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("No GPU present, Using CPU...")

No GPU present, Using CPU...


# Creating a Tensor

In [13]:
# Using Empty
t = torch.empty(2,3)
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# Check Type
type(t)

torch.Tensor

In [15]:
# Using Zeros
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Using Ones
torch.ones(2, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
# Using rand
torch.rand(2, 4)

tensor([[0.9431, 0.0478, 0.8875, 0.2049],
        [0.1253, 0.0603, 0.9977, 0.6344]])

In [21]:
# Using seed
torch.manual_seed(100)
torch.rand(2, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [22]:
torch.manual_seed(100)
torch.rand(2, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [24]:
# Using Tensor
torch.tensor([[1, 2, 3],[6, 7, 8]])

tensor([[1, 2, 3],
        [6, 7, 8]])

In [25]:
#other methods

# arange
print("using arange -->", torch.arange(0, 10))

# linspace
print("using linsapce -->", torch.linspace(0, 10, 10))

# eye
print("using eye -->", torch.eye(5))

# using full
print("using full -->", torch.full((3,3),5))

using arange --> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linsapce --> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye --> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
