# Tensor Shapes

In [2]:
import torch

In [3]:
x = torch.tensor([[1, 2, 3], [2, 4, 6]])
x

tensor([[1, 2, 3],
        [2, 4, 6]])

In [5]:
x.shape

torch.Size([2, 3])

In [6]:
# empty like - making tensor with same shape as existing tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
x.dtype

torch.int64

In [17]:
# assign data type
a = torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)
a

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
a.dtype

torch.int32

In [19]:
b = torch.tensor([1.0, 2.0, 3.0], dtype = torch.float32)
b

tensor([1., 2., 3.])

In [20]:
# find data type 
b.dtype

torch.float32

In [23]:
torch.rand_like(b)

tensor([0.5563, 0.4134, 0.1867])

In [24]:
torch.rand_like(a)

RuntimeError: "check_uniform_bounds" not implemented for 'Int'

In [27]:
# update datatype
x = x.to(torch.float32)

In [28]:
torch.rand_like(x)

tensor([[0.4162, 0.8027, 0.4930],
        [0.2445, 0.6953, 0.4065]])