# Reshaping Tensors

In [2]:
import torch
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
# Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [4]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# Permute
b = torch.rand(2, 3, 4)
b

tensor([[[0.5571, 0.3040, 0.3617, 0.9244],
         [0.1807, 0.1727, 0.3367, 0.2217],
         [0.9437, 0.7182, 0.2817, 0.0822]],

        [[0.5510, 0.9252, 0.3301, 0.5228],
         [0.8117, 0.2375, 0.7399, 0.7036],
         [0.3531, 0.5916, 0.7075, 0.0511]]])

In [6]:
b.permute(2, 0, 1)

tensor([[[0.5571, 0.1807, 0.9437],
         [0.5510, 0.8117, 0.3531]],

        [[0.3040, 0.1727, 0.7182],
         [0.9252, 0.2375, 0.5916]],

        [[0.3617, 0.3367, 0.2817],
         [0.3301, 0.7399, 0.7075]],

        [[0.9244, 0.2217, 0.0822],
         [0.5228, 0.7036, 0.0511]]])

In [13]:
# Unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [22]:
# Squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])