# Mathematical Operations

In [2]:
import torch

## 1. Scaler Operations

In [3]:
x = torch.rand(2, 4)
x

tensor([[0.5582, 0.6752, 0.0029, 0.4194],
        [0.5169, 0.0997, 0.6363, 0.0860]])

In [9]:
# addition
x+2

tensor([[2.5582, 2.6752, 2.0029, 2.4194],
        [2.5169, 2.0997, 2.6363, 2.0860]])

In [11]:
# subtraction
x -0.05

tensor([[ 0.5082,  0.6252, -0.0471,  0.3694],
        [ 0.4669,  0.0497,  0.5863,  0.0360]])

In [13]:
# multiplication
x*10

tensor([[5.5819, 6.7520, 0.0288, 4.1936],
        [5.1689, 0.9970, 6.3634, 0.8599]])

In [14]:
# division
x/0.5

tensor([[1.1164, 1.3504, 0.0058, 0.8387],
        [1.0338, 0.1994, 1.2727, 0.1720]])

In [22]:
# int division
(x *100)

tensor([[55.8189, 67.5204,  0.2877, 41.9359],
        [51.6888,  9.9697, 63.6342,  8.5993]])

In [23]:
(x * 100) // 5

tensor([[11., 13.,  0.,  8.],
        [10.,  1., 12.,  1.]])

In [24]:
# mod
((x * 100) // 5) % 2

tensor([[1., 1., 0., 0.],
        [0., 1., 0., 1.]])

In [31]:
# power
x ** 10

tensor([[2.9364e-03, 1.9695e-02, 3.8794e-26, 1.6821e-04],
        [1.3613e-03, 9.7006e-11, 1.0887e-02, 2.2113e-11]])

## 2. Element Wise Operations

In [38]:
torch.manual_seed(100)
a = torch.rand(2, 3)
b =torch.rand(2, 3)

print(a)
print(b)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [39]:
# add
a + b

tensor([[0.3744, 0.8587, 0.4706],
        [0.6019, 0.7982, 1.4895]])

In [40]:
# subtraction
a - b

tensor([[-0.1510,  0.7730,  0.0545],
        [ 0.3658,  0.5548,  0.0183]])

In [41]:
# multiplication
a * b

tensor([[0.0293, 0.0350, 0.0546],
        [0.0571, 0.0823, 0.5546]])

In [42]:
# division
a / b

tensor([[ 0.4251, 19.0441,  1.2621],
        [ 4.0994,  5.5590,  1.0249]])

In [43]:
# power
a ** b

tensor([[0.5622, 0.9913, 0.7572],
        [0.9179, 0.9536, 0.8124]])

In [44]:
# mod
a % b

tensor([[0.1117, 0.0019, 0.0545],
        [0.0117, 0.0680, 0.0183]])

In [45]:
c = torch.tensor([1, -5, 4, 45.5])

In [46]:
c

tensor([ 1.0000, -5.0000,  4.0000, 45.5000])

In [47]:
# abs
torch.abs(c)

tensor([ 1.0000,  5.0000,  4.0000, 45.5000])

In [48]:
# negative
torch.neg(c)

tensor([ -1.0000,   5.0000,  -4.0000, -45.5000])

In [49]:
# round
torch.round(c)

tensor([ 1., -5.,  4., 46.])

In [50]:
# ceil
torch.ceil(c)

tensor([ 1., -5.,  4., 46.])

In [51]:
# floor
torch.floor(c)

tensor([ 1., -5.,  4., 45.])

In [56]:
# clamp
torch.clamp(c, min=5, max=44)

tensor([ 5.,  5.,  5., 44.])

## 3. Reduction Operation

In [103]:
d = torch.randint(size = (2, 3), low=0, high=10)
d

tensor([[5, 9, 9],
        [7, 5, 9]])

In [104]:
# sum
torch.sum(d)

tensor(44)

In [105]:
# sum along columns
torch.sum(d, dim=0)

tensor([12, 14, 18])

In [106]:
# sum along rows
torch.sum(d, dim = 1)

tensor([23, 21])

In [107]:
# mean
print(d.dtype)
print(torch.mean(d, dtype = torch.float32))

# mean along column
print(torch.mean(d, dtype = torch.float32, dim=0))

# mean along row
print(torch.mean(d, dtype = torch.float32, dim=1))

torch.int64
tensor(7.3333)
tensor([6., 7., 9.])
tensor([7.6667, 7.0000])


In [108]:
# median
torch.median(d)

tensor(7)

In [109]:
# min and max
print(torch.min(d))
print(torch.max(d))

tensor(5)
tensor(9)


In [110]:
# product
torch.prod(d)

tensor(127575)

In [111]:
# standard deviation
d= d.to(torch.float32)
torch.std(d)

tensor(1.9664)

In [112]:
# Variance
torch.var(d)

tensor(3.8667)

In [113]:
# argmax
torch.argmax(d)

tensor(1)

In [114]:
# argmin
torch.argmin(d)

tensor(0)

## 4. Matrix Operations

In [130]:
f = torch.randint(size=(2, 4), low=0, high=10)
g = torch.randint(size=(4, 1), low=0, high=10)

print(f)
print(g)

tensor([[9, 8, 2, 8],
        [8, 0, 3, 5]])
tensor([[4],
        [8],
        [1],
        [4]])


In [131]:
# Matrix Multiplication
torch.matmul(f, g)

tensor([[134],
        [ 55]])

In [134]:
# Dot Product
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

print(v1)
print(v2)

tensor([1, 2])
tensor([3, 4])


In [135]:
torch.dot(v1, v2)

tensor(11)

In [136]:
# Transpose
print(f)

tensor([[9, 8, 2, 8],
        [8, 0, 3, 5]])


In [137]:
torch.transpose(f, 0, 1)

tensor([[9, 8],
        [8, 0],
        [2, 3],
        [8, 5]])

In [146]:
# Determinant
h = torch.randint(size=(2, 2), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 4.],
        [8., 1.]])

In [147]:
torch.det(h)

tensor(-27.)

In [148]:
# Inverse
torch.inverse(h)

tensor([[-0.0370,  0.1481],
        [ 0.2963, -0.1852]])

## 5. Comparison Operations

In [150]:
i = torch.randint(size=(2, 4), low=0, high=10)
j = torch.randint(size=(2, 4), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 7, 1],
        [0, 9, 6, 7]])
tensor([[8, 9, 0, 3],
        [3, 4, 8, 8]])


In [151]:
# Greater than
i > j

tensor([[False, False,  True, False],
        [False,  True, False, False]])

In [152]:
# less than
i < j

tensor([[False,  True, False,  True],
        [ True, False,  True,  True]])

In [153]:
# equal to
i == j

tensor([[ True, False, False, False],
        [False, False, False, False]])

In [154]:
# not equal to
i != j

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [155]:
# greater than equal to
i >= j

tensor([[ True, False,  True, False],
        [False,  True, False, False]])

In [156]:
# less than equal to
i <= j

tensor([[ True,  True, False,  True],
        [ True, False,  True,  True]])

## 6. Special Functions

In [157]:
k = torch.randint(size=(2, 3), low=0, high=10)
k

tensor([[1, 2, 4],
        [9, 4, 0]])

In [158]:
# log
torch.log(k)

tensor([[0.0000, 0.6931, 1.3863],
        [2.1972, 1.3863,   -inf]])

In [159]:
# exponents
torch.exp(k)

tensor([[2.7183e+00, 7.3891e+00, 5.4598e+01],
        [8.1031e+03, 5.4598e+01, 1.0000e+00]])

In [160]:
# Sqrt
torch.sqrt(k)

tensor([[1.0000, 1.4142, 2.0000],
        [3.0000, 2.0000, 0.0000]])

In [161]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.8808, 0.9820],
        [0.9999, 0.9820, 0.5000]])

In [164]:
# Softmax
k = k.to(torch.float32)
torch.softmax(k, dim=0)

tensor([[3.3535e-04, 1.1920e-01, 9.8201e-01],
        [9.9966e-01, 8.8080e-01, 1.7986e-02]])

In [167]:
# ReLu
torch.relu(k)

tensor([[1., 2., 4.],
        [9., 4., 0.]])