In [1]:
import torch

# 1. Inplace Operations

In [2]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.4243, 0.4693, 0.4990],
        [0.2089, 0.8707, 0.7142]])
tensor([[0.1784, 0.3630, 0.8637],
        [0.4152, 0.2986, 0.3441]])


In [3]:
m.add_(n)

tensor([[0.6027, 0.8323, 1.3627],
        [0.6242, 1.1693, 1.0583]])

In [4]:
m

tensor([[0.6027, 0.8323, 1.3627],
        [0.6242, 1.1693, 1.0583]])

In [5]:
m.relu_()

tensor([[0.6027, 0.8323, 1.3627],
        [0.6242, 1.1693, 1.0583]])

In [6]:
m

tensor([[0.6027, 0.8323, 1.3627],
        [0.6242, 1.1693, 1.0583]])

# 2. Copying a Tensor

In [7]:
a = torch.rand(2, 3)
a

tensor([[0.2576, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [8]:
b = a

In [9]:
b 

tensor([[0.2576, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [12]:
# PROBLEM -- not desirable

a[0][0] = 0
a

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [13]:
b

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [14]:
id(a)

3051731227008

In [15]:
id(b)

3051731227008

In [16]:
## SOLUTION

b = a.clone()

In [17]:
a

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [18]:
b

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [19]:
a[1][1] = -43
a

tensor([[  0.0000,   0.6043,   0.5664],
        [  0.9164, -43.0000,   0.2038]])

In [20]:
b

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])

In [21]:
id(a)

3051731227008

In [22]:
id(b)

3051731232048

In [23]:
a.relu_()

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.0000, 0.2038]])

In [24]:
a

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.0000, 0.2038]])

In [25]:
b

tensor([[0.0000, 0.6043, 0.5664],
        [0.9164, 0.2316, 0.2038]])