In [4]:
import torch
import torch.nn as nn

In [5]:
class Model1(nn.Module):

    def __init__(self, n_features):
        super().__init__()
        self.linear = nn.Linear(n_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        inp = self.linear(features)
        out = self.sigmoid(inp)
        return out

In [6]:
features = torch.rand(10, 5)

model1 = Model1(features.shape[1])

model1(features)

tensor([[0.5904],
        [0.6101],
        [0.5937],
        [0.5749],
        [0.6196],
        [0.5459],
        [0.5996],
        [0.6064],
        [0.5697],
        [0.6539]], grad_fn=<SigmoidBackward0>)

In [8]:
# Show model weights & bias
print("Weights --->", model1.linear.weight)
print("\nBias --->", model1.linear.bias)

Weights ---> Parameter containing:
tensor([[ 0.0202,  0.4097, -0.1532, -0.3685,  0.3665]], requires_grad=True)

Bias ---> Parameter containing:
tensor([0.2343], requires_grad=True)


In [9]:
from torchinfo import summary

In [11]:
summary(model1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
import torch
import torch.nn as nn

class Model2(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.linear1 = nn.Linear(n_features, 5)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(5, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        inp = self.linear1(features)
        out = self.relu(inp)
        inp = self.linear2(features)
        out = self.sigmoid(inp)
        return out

In [28]:
features = torch.rand(10, 5)
model2 = Model2(features.shape[1])
model2(features)

tensor([[0.6019],
        [0.6717],
        [0.6039],
        [0.6920],
        [0.6425],
        [0.6190],
        [0.6335],
        [0.6781],
        [0.5505],
        [0.6073]], grad_fn=<SigmoidBackward0>)

In [29]:
model2.linear1.weight

Parameter containing:
tensor([[-0.2865,  0.4420, -0.4323,  0.4124, -0.3772],
        [ 0.3908, -0.3589,  0.3281, -0.1098, -0.2096],
        [ 0.2295, -0.0915,  0.3075, -0.2522, -0.4276],
        [-0.0159, -0.4200, -0.2027, -0.2467, -0.1762],
        [ 0.1676,  0.3077, -0.4165, -0.2139, -0.4386]], requires_grad=True)

In [31]:
summary(model2, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 5]                   30
├─ReLU: 1-2                              [10, 5]                   --
├─Linear: 1-3                            [10, 1]                   6
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 36
Trainable params: 36
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequencial Container

In [32]:
import torch
import torch.nn as nn

In [34]:
class Model3(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(n_features, 5),
            nn.ReLU(),
            nn.Linear(5, 1),
            nn.Sigmoid(),
        )
    def forward(self, features):
        out = self.network(features)
        return out

In [37]:
model3 = Model3(features.shape[1])
model3(features)

tensor([[0.4546],
        [0.4325],
        [0.4562],
        [0.4196],
        [0.4768],
        [0.4407],
        [0.4476],
        [0.4345],
        [0.4681],
        [0.4736]], grad_fn=<SigmoidBackward0>)